baseURL: /
relativeURLs: true
languageCode: en-us
title: Dhali

themesDir: auth-by-pay/themes

module:
  # uncomment line below for local development of module
  # workspace: hugo.work
  imports:
    path: hugo-fresh


googleAnalytics: # Put in your tracking code without quotes like this: UA-XXX for universal tracking or G-XXX analytics v4 tracking
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  # navbarlogo:
  # # Logo (from static/images/logos/___)
  #   image: illustrations/dhali-logo.png
  #   link: /
  #   # Default width/height. Uncomment if you need to change
  #   width: 35
  #   height: 20
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    buttonLink: https://dhali-app.web.app/
    buttonText: Try it now
    # Main hero title
    title: Monetise in minutes
    subtitle: Add Web3 monetisation to your APIs in minutes
    # Hero image (from static/images/___)
    image: illustrations/dhali-logo.png
    # Footer logos (from static/images/logos/clients/*.svg)
    # urls are optional
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Why Dhali?
    url: "#section4"
  - title: How it works
    url: "#section3"
  - title: Docs
    url: "/docs"
  - title: Marketplace
    url: "https://dhali-app.web.app"
    button: true
  # - title: Get started
  #   url: "#section3"
  #   button: true
  section4:
    title: Why Dhali?
    subtitle: We are faster, cheaper, more flexibile, and transparent
    clients:
    - name: Other platforms
      quote: 
        - "1-3% transaction fees"
        - "Multi-day settlement"
        - "Expensive auditing and accounting"
        - "Manual API key management"
        - "You are responsible for securing payments and client information"
        - "Delayed time-to-market"
      job: Accountant
      img: 1
    - name: Dhali
      quote: 
        - "0.5% transaction fees"
        - "Efficient, real-time payment streaming technology"
        - "Transactions are audit-able on blockchain"
        - "No API key management"
        - "No client information to secure"
        - "Monetise your APIs immediately"
      job: Financial Analyst
      img: 2
    valueProps:
    - text: "Easy to use"
      subText: Just link your wallet and API, that's it
      icon: thumb_up
    - text: "Reduce costs by 70%"
      subText: Blockchain lowers fees for all
      icon: monetization_on
    - text: "Improve time to market"
      subText: No more Web 2.0 hurdles or delays
      icon: watch
    - text: "Access new customers"
      subText: Instantly achieve global reach
      icon: public
    - text: "Less burden"
      subText: Managing customer data is a thing of the past
      icon: check
    - text: "Privacy and security"
      subText: Blockchain security with off-ledger payments
      icon: lock
  section3:
    title: How does is work?
    subtitle: "Efficient, layer-2 blockchain transactions"
    image: illustrations/users.png
    buttonText: Try it now
    buttonLink: "https://dhali-app.web.app"
  footer:
    # Logo (from /images/logos/___)
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://twitter.com/dhali_io
      icon: twitter
    - link: https://www.linkedin.com/company/98120426
      icon: linkedin
    - link: https://www.youtube.com/channel/UC8Mx_KbOQ4E7y50mSmlTx4w
      icon: youtube
    - link: https://discord.gg/smBNMzPT
      icon: discord
    bulmalogo: false
    quicklinks:
      column1:
        title: "Blog"
        links:
        - text: Latest news
          link: https://dhali.substack.com/
