name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Inject GTM snippets
        run: |
          GTM_STAGING_HEAD_SNIPPET=$(cat gtm/gtm_head_staging.html)
          GTM_STAGING_BODY_SNIPPET=$(cat gtm/gtm_body_staging.html)
          perl -i -pe "s#<!-- GTM_HEAD -->#${GTM_STAGING_HEAD_SNIPPET}#gs" index.html
          perl -i -pe "s#<!-- GTM_BODY -->#${GTM_STAGING_BODY_SNIPPET}#gs" index.html
          perl -i -pe "s#<!-- GTM_HEAD -->#${GTM_STAGING_HEAD_SNIPPET}#gs" blog/index.html
          perl -i -pe "s#<!-- GTM_BODY -->#${GTM_STAGING_BODY_SNIPPET}#gs" blog/index.html
          perl -i -pe "s#<!-- GTM_HEAD -->#${GTM_STAGING_HEAD_SNIPPET}#gs" docs/index.html
          perl -i -pe "s#<!-- GTM_BODY -->#${GTM_STAGING_BODY_SNIPPET}#gs" docs/index.html
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KERNML }}'
          projectId: kernml
