name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Inject GTM snippets
        run: |
          GTM_PROD_HEAD_SNIPPET=$(cat gtm/gtm_head_prod.html)
          GTM_PROD_BODY_SNIPPET=$(cat gtm/gtm_body_prod.html)
          perl -i -pe "s#<!-- GTM_HEAD -->#${GTM_PROD_HEAD_SNIPPET}#gs" index.html
          perl -i -pe "s#<!-- GTM_BODY -->#${GTM_PROD_BODY_SNIPPET}#gs" index.html
          perl -i -pe "s#<!-- GTM_HEAD -->#${GTM_PROD_HEAD_SNIPPET}#gs" blog/index.html
          perl -i -pe "s#<!-- GTM_BODY -->#${GTM_PROD_BODY_SNIPPET}#gs" blog/index.html
          perl -i -pe "s#<!-- GTM_HEAD -->#${GTM_PROD_HEAD_SNIPPET}#gs" docs/index.html
          perl -i -pe "s#<!-- GTM_BODY -->#${GTM_PROD_BODY_SNIPPET}#gs" docs/index.html
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true
      - name: Build landing page
        run: hugo --gc --minify --templateMetrics --templateMetricsHints --buildDrafts --buildExpired --buildFuture --forceSyncStatic --destination .
      - name: Build auth-by-pay
        working-directory: ./auth-by-pay
        run: hugo --gc --minify --templateMetrics --templateMetricsHints --buildDrafts --buildExpired --buildFuture --forceSyncStatic --destination .
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DHALI_PROD }}'
          channelId: live
          projectId: dhali-prod
