name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      k name: Inject GTM snippets
        run: |
          GTM_STAGING_HEAD_SNIPPET=$(cat gtm/gtm_head_staging.html)
          GTM_STAGING_BODY_SNIPPET=$(cat gtm/gtm_body_staging.html)
          perl -i -pe "s#<!-- GTM_HEAD -->#${GTM_STAGING_HEAD_SNIPPET}#gs" index.html
          perl -i -pe "s#<!-- GTM_BODY -->#${GTM_STAGING_BODY_SNIPPET}#gs" index.html
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KERNML }}'
          channelId: live
          projectId: kernml
